apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - name: container-image
        resources: {}
status: {}
